services:
  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    depends_on:
      - proto-compiler

  order-service:
    build: ./order-service
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=user-service:50051

  proto-compiler:
    build:
      context: .
      dockerfile: Dockerfile.proto
    volumes:
      - ./proto:/app/proto
      - ./proto-gen:/app/proto-gen
    command: >
      sh -c "protoc --go_out=proto-gen --go-grpc_out=proto-gen proto/*.proto"