version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=http://user-service:8081 # Not 'localhost' because the services are running inside Docker containers, and Docker Compose provides an internal network for communication between containers.
                                                  # If the services are moved to a different environment (e.g., staging or production), you don't need to hardcode or update localhost or IP addresses.
                                                  # Docker's internal DNS resolves the service names automatically, making the setup more robust and easier to manage.