FROM golang:1.20

# Install protoc
RUN apt-get update && apt-get install -y \
    unzip \
    && apt-get clean

# Download and install protoc
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip && \
    unzip protoc-21.12-linux-x86_64.zip -d /usr/local && \
    rm -f protoc-21.12-linux-x86_64.zip

# Install Go plugins for protoc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

# Add Go binaries to PATH
ENV PATH=$PATH:/go/bin

WORKDIR /app